FROM puterstructions/base:20161108-2100
MAINTAINER Jason+Python3_Dockerfile@PuterStructions.Com
ENV PYTHON3_IMAGE_BUILT_AFTER 20161108-2100

RUN apt-get install -y \
    python3 \
    python3-dev \
    python-distribute \
    python3-pip
    
RUN pip3 install \
    ipython \
    pdb
